import { Announcement, ServantRoster, InventoryItem, Sermon, GalleryItem, MinistryRequest } from '@/types';

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  // === AKAN DATANG (eventDate >= 2026-08-31, hari ini) ===
  {
    id: 'ann-1',
    title: 'Ibadah Raya Minggu — Tema: Bertumbuh Dalam Kasih & Pengharapan',
    category: 'general',
    content: 'Mari hadir bersama keluarga dalam Ibadah Raya Minggu. Pembicara: Pdt. Yohanes Sutono, S.Th., M.Ag. Dilayani oleh Tim Musik DS Worship. Bertempat di Gedung Utama.',
    eventDate: '2026-09-06',
    endDate: '2026-09-06',
    isPinned: true,
    isPublished: true,
    badgeText: 'Minggu Depan',
    author: 'Sekretariat GIA Deliksari',
    createdAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'Ibadah Youth (Grow Generation) — Sabtu Sore',
    category: 'youth',
    content: 'Ibadah Youth mingguan untuk seluruh pemuda & remaja. Pembicara: Sdr. Noel Yosan Loveano, S.Th. Bertempat di Gedung Utama atau Ruang Bethel. Latihan musik sore sebelumnya pukul 16.30 WIB.',
    eventDate: '2026-09-12',
    endDate: '2026-09-12',
    isPinned: false,
    isPublished: true,
    badgeText: 'Youth Event',
    author: 'Tim PRBK Grow Generation',
    createdAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'ann-3',
    title: 'COC Kidz: Sekolah Minggu + Aktivitas Kreatif',
    category: 'kidz',
    content: 'Ibadah Sekolah Minggu untuk anak-anak Balita – SD dengan pembelajaran Alkitab, pujian, dan aktivitas kreatif sesuai usia. Bertempat di Ruang Bethel pukul 09.30 – 10.30 WIB.',
    eventDate: '2026-09-06',
    endDate: '2026-09-06',
    isPinned: false,
    isPublished: true,
    badgeText: 'Sekolah Minggu',
    author: 'Tim Guru KAA — Sdri. Yemima P.',
    createdAt: '2026-08-28T10:00:00Z',
  },
  {
    id: 'ann-4',
    title: 'Ibadah Wanita HANA — Jumat Sore',
    category: 'hana',
    content: 'Persekutuan kaum wanita & ibu-ibu Hana Fellowship. Dilayani oleh Ibu Santini Lidyawati & tim pengurus Hana (Ibu Penskilla, Ibu Siska, Ibu Sulistya). Bertempat di Gedung Utama pukul 17.30 – 19.00 WIB.',
    eventDate: '2026-09-04',
    endDate: '2026-09-04',
    isPinned: false,
    isPublished: true,
    badgeText: 'Ibadah Wanita',
    author: 'Pengurus Hana',
    createdAt: '2026-08-28T11:00:00Z',
  },
  {
    id: 'ann-5',
    title: 'Pemeriksaan Kesehatan Gratis Jemaat & Warga',
    category: 'general',
    content: 'Pelayanan kasih masyarakat berupa cek gula darah, tensi, dan konsultasi kesehatan cuma-cuma seusai ibadah minggu.',
    eventDate: '2026-09-13',
    endDate: '2026-09-13',
    isPinned: false,
    isPublished: true,
    badgeText: 'Bulan Ini',
    author: 'Diakonia GIA Deliksari',
    createdAt: '2026-08-28T12:00:00Z',
  }
  // === CATATAN: warta yang sudah berlalu (eventDate < hari ini)
  //     TIDAK ditampilkan di landing publik — lihat AnnouncementBoard.tsx
  //     filter `isPublished` + waktu. Tersimpan di Supabase untuk arsip admin. ===
];

export const INITIAL_ROSTER: ServantRoster[] = [
  // === Ibadah Raya Minggu (06 September 2026) ===
  {
    id: 'rst-1',
    serviceCategory: 'general',
    serviceDate: '2026-09-06',
    role: 'Pengkhotbah',
    servantName: 'Pdt. Yohanes Sutono, S.Th., M.Ag.',
    phone: '08123456789',
    status: 'confirmed',
    notes: 'Ibadah Raya Minggu — Gedung Utama',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-2',
    serviceCategory: 'general',
    serviceDate: '2026-09-06',
    role: 'Worship Leader (WL)',
    servantName: 'Bro. Andreas & Sis. Maria',
    phone: '08123456790',
    status: 'confirmed',
    notes: 'Latihan musik Sabtu 19.00 WIB',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-3',
    serviceCategory: 'general',
    serviceDate: '2026-09-06',
    role: 'Pemain Musik / Full Band',
    servantName: 'DS Worship Team (Korg primary, Medeli filler, Bass, Gitar Visioner, Drum Akustik Visioner + Pad)',
    phone: '08123456791',
    status: 'confirmed',
    notes: 'Soundcheck Minggu 06.30 WIB',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-4',
    serviceCategory: 'general',
    serviceDate: '2026-09-06',
    role: 'Multimedia / Operator Slide',
    servantName: 'David & Tim Media',
    phone: '08123456792',
    status: 'confirmed',
    notes: 'Persiapkan lirik lagu & tayangan warta',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-5',
    serviceCategory: 'general',
    serviceDate: '2026-09-06',
    role: 'Usher & Kolektan',
    servantName: 'Bpk. Budi, Ibu Lisa, Bpk. Hendra',
    phone: '08123456793',
    status: 'confirmed',
    notes: 'Menyambut jemaat & mengelola 3 kotak persembahan',
    createdAt: '2026-08-28T00:00:00Z',
  },

  // === COC Kidz (Sekolah Minggu) ===
  {
    id: 'rst-6',
    serviceCategory: 'kidz',
    serviceDate: '2026-09-06',
    role: 'Ketua / Guru Cerita Firman',
    servantName: 'Sdri. Yemima Purnamasari',
    phone: '08123456794',
    status: 'confirmed',
    notes: 'Bertempat di Ruang Bethel',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-7',
    serviceCategory: 'kidz',
    serviceDate: '2026-09-06',
    role: 'Sekretaris',
    servantName: 'Sdri. Kesya',
    phone: '08123456795',
    status: 'confirmed',
    notes: 'Absensi & buku kegiatan anak',
    createdAt: '2026-08-28T00:00:00Z',
  },

  // === Youth (Grow Generation) - Sabtu 29 Agustus 2026 = Ibadah YOUTH ===
  // Pola 4-minggu: 29 Ags = Youth, 5 Sep = Komsel, 12 Sep = Youth, 19 Sep = Komsel
  {
    id: 'rst-8',
    serviceCategory: 'youth',
    serviceDate: '2026-08-29',
    role: 'Pembicara / Firman Youth',
    servantName: 'Sdr. Noel Yosan Loveano, S.Th. (Youth Pastor)',
    phone: '08123456796',
    status: 'confirmed',
    notes: 'Ibadah Youth (Sabtu ke-1 bulan September) — Gedung Utama',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-9',
    serviceCategory: 'youth',
    serviceDate: '2026-08-29',
    role: 'Ketua Youth',
    servantName: 'Sdri. Lara Tampubolon',
    phone: '08123456797',
    status: 'confirmed',
    notes: 'Koordinasi keseluruhan ibadah Youth',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-10',
    serviceCategory: 'youth',
    serviceDate: '2026-09-12',
    role: 'Pembicara / Firman Youth',
    servantName: 'Sdr. Noel Yosan Loveano, S.Th. (Youth Pastor)',
    phone: '08123456796',
    status: 'confirmed',
    notes: 'Ibadah Youth (Sabtu ke-3 bulan September)',
    createdAt: '2026-08-28T00:00:00Z',
  },

  // === Hana (Wanita) - Jumat 4 September 2026 = Ibadah HANA ===
  // Pola 4-minggu: 4 Sep = Hana, 11 Sep = Hana, 18 Sep = Hana, 25 Sep = Hana
  // (Jumat hanya untuk HANA; Komsel Ekklesia di Selasa)
  {
    id: 'rst-11',
    serviceCategory: 'hana',
    serviceDate: '2026-09-04',
    role: 'Pembina & Doa Hana Fellowship',
    servantName: 'Ibu Santini Lidyawati',
    phone: '08123456798',
    status: 'confirmed',
    notes: 'Ibadah HANA pertama bulan September — Gedung Utama 17.30 WIB',
    createdAt: '2026-08-28T00:00:00Z',
  },
  {
    id: 'rst-12',
    serviceCategory: 'hana',
    serviceDate: '2026-09-04',
    role: 'Ketua Hana',
    servantName: 'Ibu Penskilla',
    phone: '08123456799',
    status: 'confirmed',
    notes: 'Koordinasi jemaat wanita & persiapan',
    createdAt: '2026-08-28T00:00:00Z',
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  // === SOUND SYSTEM ===
  {
    id: 'inv-1',
    name: 'Mixer Newbaxs CT80S (Utama)',
    category: 'Sound System',
    code: 'MIX-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Bilik Sound Belakang',
    lastCheckedAt: '2026-08-22 18:00',
    checkedBy: 'Tim Sound',
    notes: 'Mixer utama untuk ibadah raya & event besar',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-2',
    name: 'Mixer Hardwell SLK8 (Sekunder/Portable)',
    category: 'Sound System',
    code: 'MIX-02',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Bilik Sound Belakang',
    lastCheckedAt: '2026-08-22 18:05',
    checkedBy: 'Tim Sound',
    notes: 'Untuk ibadah kecil/komsel di Ruang Bethel',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-3',
    name: 'Power Amplifier New XYS SQ7200H',
    category: 'Sound System',
    code: 'PWR-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Bilik Sound Belakang',
    lastCheckedAt: '2026-08-22 18:10',
    checkedBy: 'Tim Sound',
    notes: 'Power amplifier utama, driver speaker utama',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-4',
    name: 'Wireless Mic WL (Set untuk Worship Leader)',
    category: 'Sound System',
    code: 'MIC-WL-01',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Meja Sound Operator (Depan)',
    lastCheckedAt: '2026-08-22 17:30',
    checkedBy: 'Tim Multimedia',
    notes: 'Mic WL utama + cadangan',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-5',
    name: 'Wireless Mic Singer (Set)',
    category: 'Sound System',
    code: 'MIC-SNG-01',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Meja Sound Operator (Depan)',
    lastCheckedAt: '2026-08-22 17:30',
    checkedBy: 'Tim Multimedia',
    notes: 'Mic untuk singer/solo',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // === MULTIMEDIA & KAMERA ===
  {
    id: 'inv-6',
    name: 'Proyektor Utama Ruang Ibadah & Screen Motorized',
    category: 'Multimedia & Kamera',
    code: 'PRJ-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Plafon Tengah Sanctuary',
    lastCheckedAt: '2026-08-22 18:15',
    checkedBy: 'Tim Media',
    notes: 'Kabel HDMI & konverter berfungsi normal',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-7',
    name: 'Kamera Live Streaming PTZ / Camcorder Sony',
    category: 'Multimedia & Kamera',
    code: 'CAM-01',
    quantity: 2,
    isChecked: false,
    condition: 'good',
    location: 'Tripod Balkon Belakang',
    notes: 'Perlu cek capture card OBS sebelum live streaming',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // === ALAT MUSIK ===
  {
    id: 'inv-8',
    name: 'Keyboard Korg (Primary)',
    category: 'Alat Musik',
    code: 'MUS-KEY-KORG',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kiri',
    lastCheckedAt: '2026-08-22 17:45',
    checkedBy: 'Tim Musik',
    notes: 'Keyboard utama untuk ibadah raya & event. DI Box + Jack 6.5mm terpasang',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-9',
    name: 'Keyboard Medeli (Filler)',
    category: 'Alat Musik',
    code: 'MUS-KEY-MED',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kiri',
    lastCheckedAt: '2026-08-22 17:46',
    checkedBy: 'Tim Musik',
    notes: 'Keyboard filler/pelengkap. Optional, kadang ada kadang tidak',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-10',
    name: 'Bass Elektrik',
    category: 'Alat Musik',
    code: 'MUS-BASS-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kanan',
    lastCheckedAt: '2026-08-22 17:48',
    checkedBy: 'Tim Musik',
    notes: 'Bass line untuk full band',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-11',
    name: 'Gitar Visioner',
    category: 'Alat Musik',
    code: 'MUS-GTR-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kanan',
    lastCheckedAt: '2026-08-22 17:49',
    checkedBy: 'Tim Musik',
    notes: 'Gitar untuk full band & ibadah akustik',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-12',
    name: 'Drum Akustik Visioner Set + Shield',
    category: 'Alat Musik',
    code: 'MUS-DRM-AK',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kanan',
    lastCheckedAt: '2026-08-22 17:50',
    checkedBy: 'Tim Musik',
    notes: 'Drum utama untuk full band. Semua mic drum terpasang dan balance',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-13',
    name: 'Drum Pad (Elektronik)',
    category: 'Alat Musik',
    code: 'MUS-DRM-PAD',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kanan',
    lastCheckedAt: '2026-08-22 17:51',
    checkedBy: 'Tim Musik',
    notes: 'Drum elektronik tambahan — 1 ekosistem dengan drum akustik',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-14',
    name: 'Kajon (Cajón)',
    category: 'Alat Musik',
    code: 'MUS-KAJON-01',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Ruang Bethel',
    lastCheckedAt: '2026-08-22 17:55',
    checkedBy: 'Tim Musik',
    notes: 'Perkusi akustik untuk ibadah akustik di Ruang Bethel',
    createdAt: '2026-08-01T00:00:00Z',
  },

  // === IBADAH & RUANGAN ===
  {
    id: 'inv-15',
    name: 'Nampan & Cawan Perjamuan Kudus Stainless',
    category: 'Ibadah & Ruangan',
    code: 'IBD-PK-01',
    quantity: 4,
    isChecked: false,
    condition: 'good',
    location: 'Ruang Pastori / Lemari Sakramen',
    notes: 'Disiapkan untuk ibadah minggu perjamuan',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-16',
    name: 'Kotak Persembahan (3 unit: Persembahan 1, 2, Khusus)',
    category: 'Ibadah & Ruangan',
    code: 'IBD-KOL-01',
    quantity: 3,
    isChecked: true,
    condition: 'good',
    location: 'Meja Penerima Tamu (Lobi)',
    lastCheckedAt: '2026-08-22 16:00',
    checkedBy: 'Ibu Lisa',
    notes: 'Kotak 1 = persembahan umum, Kotak 2 = persembahan umum, Kotak Khusus = untuk program/misi',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-17',
    name: 'AC Ruang Utama 2 PK (Unit 1 & 2)',
    category: 'Ibadah & Ruangan',
    code: 'FCL-AC-01',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Dinding Samping Kiri & Kanan Sanctuary',
    lastCheckedAt: '2026-08-22 17:00',
    checkedBy: 'Bpk. Hendra',
    notes: 'Suhu diset 22°C remote tersimpan di meja operator',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-18',
    name: 'QRIS Standee / Standing Banner Persembahan',
    category: 'Ibadah & Ruangan',
    code: 'IBD-QRIS-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Meja Penerima Tamu',
    lastCheckedAt: '2026-08-22 16:05',
    checkedBy: 'Ibu Lisa',
    notes: 'QRIS untuk metode persembahan digital. Code QR ditempel di standee',
    createdAt: '2026-08-01T00:00:00Z',
  }
];

export const INITIAL_SERMONS: Sermon[] = [
  {
    id: 'srm-1',
    title: 'Bertumbuh Kuat di Tengah Badai Kehidupan',
    speaker: 'Ps. Yohanes Sutono',
    passage: 'Kolose 2:6-7 & Mazmur 1:1-3',
    date: 'Minggu, 16 Agustus 2026',
    youtubeUrl: 'https://www.youtube.com/@GIADeliksariSemarang',
    thumbnail: '/images/gallery-2.jpg',
    category: 'Ibadah Raya',
    createdAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'srm-2',
    title: 'Generasi yang Menyala Bagi Kemuliaan Kristus',
    speaker: 'Kak Noel Yosan, S.Th.',
    passage: '1 Timotius 4:12',
    date: 'Sabtu, 15 Agustus 2026',
    youtubeUrl: 'https://www.youtube.com/@GIADeliksariSemarang',
    thumbnail: '/images/gallery-6.jpg',
    category: 'Grow Generation Youth',
    createdAt: '2026-08-15T19:00:00Z',
  },
  {
    id: 'srm-3',
    title: 'Keluarga Beriman yang Berakar dalam Kasih',
    speaker: 'Ps. Yohanes Sutono',
    passage: 'Yosua 24:15 & Efesus 5:1-2',
    date: 'Minggu, 9 Agustus 2026',
    youtubeUrl: 'https://www.youtube.com/@GIADeliksariSemarang',
    thumbnail: '/images/gallery-5.jpg',
    category: 'Ibadah Raya',
    createdAt: '2026-08-09T10:00:00Z',
  }
];

export const INITIAL_GALLERY: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Gedung Sanctuary GIA Deliksari Semarang',
    category: 'ibadah',
    image: '/images/gallery-1.jpg',
    date: 'Agustus 2026',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-2',
    title: 'Pemberitaan Firman & Penggembalaan Jemaat',
    category: 'ibadah',
    image: '/images/gallery-2.jpg',
    date: 'Agustus 2026',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'gal-3',
    title: 'Praise & Worship DS Worship Team',
    category: 'worship',
    image: '/images/gallery-3.jpg',
    date: 'Juli 2026',
    createdAt: '2026-07-15T00:00:00Z',
  },
  {
    id: 'gal-4',
    title: 'Keceriaan Ibadah Anak Sekolah Minggu COC Kidz',
    category: 'komunitas',
    image: '/images/gallery-4.jpg',
    date: 'Juli 2026',
    createdAt: '2026-07-15T00:00:00Z',
  },
  {
    id: 'gal-5',
    title: 'Persekutuan & Doa Bersama Jemaat',
    category: 'komunitas',
    image: '/images/gallery-5.jpg',
    date: 'Juni 2026',
    createdAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'gal-6',
    title: 'Fellowship Pemuda Grow Generation PRBK',
    category: 'youth',
    image: '/images/gallery-6.jpg',
    date: 'Juni 2026',
    createdAt: '2026-06-20T00:00:00Z',
  },
];

export const INITIAL_MINISTRY_REQUESTS: MinistryRequest[] = [
  {
    id: 'req-1',
    type: 'prayer',
    name: 'Budi Santoso',
    phone: '081234567891',
    subType: 'Doa Kesembuhan',
    message: 'Mohon dukungan doa untuk kesembuhan ibu saya yang sedang dirawat.',
    needPastoralVisit: true,
    status: 'in_progress',
    createdAt: '2026-08-22T08:30:00Z',
  },
  {
    id: 'req-2',
    type: 'sacrament',
    name: 'Maria Stephanie',
    phone: '081234567892',
    subType: 'Baptisan Selam',
    message: 'Ingin dibaptis selam pada gelombang baptisan berikutnya.',
    needPastoralVisit: false,
    status: 'new',
    createdAt: '2026-08-23T04:15:00Z',
  },
  {
    id: 'req-3',
    type: 'volunteer',
    name: 'Kevin Pratama',
    phone: '081234567893',
    subType: 'Multimedia & Operator Slide',
    message: 'Rindu melayani di bagian slide & proyektor ibadah raya.',
    needPastoralVisit: false,
    status: 'completed',
    createdAt: '2026-08-20T11:00:00Z',
  }
];
