import { Announcement, ServantRoster, InventoryItem } from '@/types';

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Ibadah Raya Minggu & Perjamuan Kudus',
    category: 'general',
    content: 'Mari hadir bersama keluarga dalam Ibadah Raya Minggu ini. Kita akan bersama-sama merayakan Perjamuan Kudus dan menerima pesan firman Tuhan yang menguatkan.',
    eventDate: '2026-08-30',
    endDate: '2026-08-30',
    isPinned: true,
    isPublished: true,
    badgeText: 'Penting / Khusus',
    author: 'Sekretariat GIA Deliksari',
    createdAt: '2026-08-20T08:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'Grow Generation Youth Camp & Gathering 2026',
    category: 'youth',
    content: 'Panggilan untuk seluruh kaum muda & remaja! Jangan lewatkan Youth Gathering penuh sukacita dan pembekalan rohani. Pendaftaran dibuka melalui panitia PRBK.',
    eventDate: '2026-09-05',
    endDate: '2026-09-06',
    isPinned: true,
    isPublished: true,
    badgeText: 'Youth Event',
    author: 'Tim PRBK Grow Generation',
    createdAt: '2026-08-21T10:00:00Z',
  },
  {
    id: 'ann-3',
    title: 'COC Kidz: Festival Sukacita & Kreasi Anak',
    category: 'kidz',
    content: 'Ibadah Sekolah Minggu KAA / COC Kidz minggu depan akan diramaikan dengan aktivitas kreasi Alkitab dan panggung boneka. Bawa teman-temanmu ya!',
    eventDate: '2026-08-30',
    endDate: '2026-08-30',
    isPinned: false,
    isPublished: true,
    badgeText: 'Sekolah Minggu',
    author: 'Tim Guru KAA',
    createdAt: '2026-08-22T09:30:00Z',
  },
  {
    id: 'ann-4',
    title: 'Persekutuan Wanita Hana: Doa & Berbagi Kasih',
    category: 'hana',
    content: 'Persekutuan kaum wanita & ibu-ibu Hana Fellowship akan diadakan pada hari Selasa pukul 16.30 WIB di Ruang Serbaguna GIA Deliksari.',
    eventDate: '2026-09-01',
    endDate: '2026-09-01',
    isPinned: false,
    isPublished: true,
    badgeText: 'Kaum Wanita',
    author: 'Pengurus Hana',
    createdAt: '2026-08-19T14:00:00Z',
  },
  {
    id: 'ann-5',
    title: 'Pemeriksaan Kesehatan Gratis Jemaat & Warga',
    category: 'general',
    content: 'Pelayanan kasih masyarakat berupa cek gula darah, tensi, dan konsultasi kesehatan cuma-cuma seusai ibadah minggu kedua bulan depan.',
    eventDate: '2026-09-13',
    endDate: '2026-09-13',
    isPinned: false,
    isPublished: true,
    badgeText: 'Bulan Ini',
    author: 'Diakonia GIA Deliksari',
    createdAt: '2026-08-22T11:00:00Z',
  }
];

export const INITIAL_ROSTER: ServantRoster[] = [
  // General Service
  {
    id: 'rst-1',
    serviceCategory: 'general',
    serviceDate: '2026-08-30',
    role: 'Pengkhotbah',
    servantName: 'Ps. Yohanes Sutono',
    phone: '08123456789',
    status: 'confirmed',
    notes: 'Tema: Bertumbuh Dalam Kasih & Pengharapan',
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'rst-2',
    serviceCategory: 'general',
    serviceDate: '2026-08-30',
    role: 'Worship Leader (WL)',
    servantName: 'Bro. Andreas & Sis. Maria',
    phone: '08123456790',
    status: 'confirmed',
    notes: 'Latihan Sabtu pukul 18.00 WIB',
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'rst-3',
    serviceCategory: 'general',
    serviceDate: '2026-08-30',
    role: 'Pemain Musik / Band',
    servantName: 'DS Worship Team (Keyboard, Bass, Drum, Guitar)',
    phone: '08123456791',
    status: 'confirmed',
    notes: 'Soundcheck Minggu 06.30 WIB',
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'rst-4',
    serviceCategory: 'general',
    serviceDate: '2026-08-30',
    role: 'Multimedia / Operator Slide',
    servantName: 'David & Tim Media',
    phone: '08123456792',
    status: 'confirmed',
    notes: 'Persiapkan lirik lagu & tayangan warta',
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'rst-5',
    serviceCategory: 'general',
    serviceDate: '2026-08-30',
    role: 'Usher & Kolektan',
    servantName: 'Bpk. Budi, Ibu Lisa, Bpk. Hendra',
    phone: '08123456793',
    status: 'confirmed',
    notes: 'Menyambut jemaat di pintu depan',
    createdAt: '2026-08-20T00:00:00Z',
  },

  // Kidz (COC Kidz)
  {
    id: 'rst-6',
    serviceCategory: 'kidz',
    serviceDate: '2026-08-30',
    role: 'Guru Cerita Firman',
    servantName: 'Kak Kariani Giawa',
    phone: '08123456794',
    status: 'confirmed',
    notes: 'Cerita: Daud yang Berani',
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'rst-7',
    serviceCategory: 'kidz',
    serviceDate: '2026-08-30',
    role: 'Pemandu Pujian / WL Cilik',
    servantName: 'Kak Cindy & Kak Rian',
    phone: '08123456795',
    status: 'confirmed',
    notes: 'Gerak dan lagu anak',
    createdAt: '2026-08-20T00:00:00Z',
  },

  // Youth (Grow Generation)
  {
    id: 'rst-8',
    serviceCategory: 'youth',
    serviceDate: '2026-08-29',
    role: 'Pembicara Youth',
    servantName: 'Ps. Yohanes Sutono',
    phone: '08123456796',
    status: 'confirmed',
    notes: 'Sabtu sore pukul 17.00 WIB',
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'rst-9',
    serviceCategory: 'youth',
    serviceDate: '2026-08-29',
    role: 'Worship Leader & Band Youth',
    servantName: 'Grow Gen Band',
    phone: '08123456797',
    status: 'confirmed',
    notes: 'Lagu kontemporer pemuda',
    createdAt: '2026-08-20T00:00:00Z',
  },

  // Hana (Wanita)
  {
    id: 'rst-10',
    serviceCategory: 'hana',
    serviceDate: '2026-09-01',
    role: 'Pemimpin Pujian Hana',
    servantName: 'Ibu Sarah Sutono',
    phone: '08123456798',
    status: 'confirmed',
    notes: 'Ibadah Selasa Sore',
    createdAt: '2026-08-20T00:00:00Z',
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Wireless Microphone Shure Beta 58A (Set 1)',
    category: 'Sound System',
    code: 'MIC-01',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Meja Sound Operator (Depan)',
    lastCheckedAt: '2026-08-22 17:30',
    checkedBy: 'Tim Multimedia',
    notes: 'Baterai sudah diganti baru tipe AA Panasonic',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-2',
    name: 'Wireless Microphone Shure (Set 2)',
    category: 'Sound System',
    code: 'MIC-02',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Meja Sound Operator (Depan)',
    lastCheckedAt: '2026-08-22 17:30',
    checkedBy: 'Tim Multimedia',
    notes: 'Untuk Singer / Cadangan',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-3',
    name: 'Digital Mixer Behringer X32',
    category: 'Sound System',
    code: 'MIX-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Bilik Sound Belakang',
    lastCheckedAt: '2026-08-22 18:00',
    checkedBy: 'Budi Sound',
    notes: 'Scene ibadah minggu sudah diload',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-4',
    name: 'Proyektor Utama Ruang Ibadah & Screen Motorized',
    category: 'Multimedia & Kamera',
    code: 'PRJ-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Plafon Tengah Sanctuary',
    lastCheckedAt: '2026-08-22 18:15',
    checkedBy: 'David Media',
    notes: 'Kabel HDMI & konverter berfungsi normal',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-5',
    name: 'Kamera Live Streaming PTZ / Camcorder Sony',
    category: 'Multimedia & Kamera',
    code: 'CAM-01',
    quantity: 2,
    isChecked: false,
    condition: 'good',
    location: 'Tripod Balkon Belakang',
    notes: 'Perlu cek capture card OBS sebelum live streaming',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-6',
    name: 'Keyboard Roland RD-88 + Sustain Pedal + Adaptor',
    category: 'Alat Musik',
    code: 'MUS-KEY-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kiri',
    lastCheckedAt: '2026-08-22 17:45',
    checkedBy: 'Tim Musik',
    notes: 'DI Box & Jack 6.5mm terpasang',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-7',
    name: 'Drum Akustik Set + Drum Shield Akrilik',
    category: 'Alat Musik',
    code: 'MUS-DRM-01',
    quantity: 1,
    isChecked: true,
    condition: 'good',
    location: 'Panggung Kanan',
    lastCheckedAt: '2026-08-22 17:50',
    checkedBy: 'Tim Musik',
    notes: 'Semua mic drum terpasang dan balance',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-8',
    name: 'Nampan & Cawan Perjamuan Kudus Stainless',
    category: 'Ibadah & Ruangan',
    code: 'IBD-PK-01',
    quantity: 4,
    isChecked: false,
    condition: 'good',
    location: 'Ruang Pastori / Lemari Sakramen',
    notes: 'Disiapkan untuk ibadah minggu perjamuan',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-9',
    name: 'Kantong Kolekte / Persembahan Merah Maroon',
    category: 'Ibadah & Ruangan',
    code: 'IBD-KOL-01',
    quantity: 6,
    isChecked: true,
    condition: 'good',
    location: 'Meja Penerima Tamu',
    lastCheckedAt: '2026-08-22 16:00',
    checkedBy: 'Ibu Lisa',
    notes: 'Bersih & siap di meja usher',
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inv-10',
    name: 'AC Ruang Utama 2 PK (Unit 1 & 2)',
    category: 'Ibadah & Ruangan',
    code: 'FCL-AC-01',
    quantity: 2,
    isChecked: true,
    condition: 'good',
    location: 'Dinding Samping Kiri & Kanan',
    lastCheckedAt: '2026-08-22 17:00',
    checkedBy: 'Bpk. Hendra',
    notes: 'Suhu diset 22°C remote tersimpan di meja operator',
    createdAt: '2026-08-01T00:00:00Z',
  }
];
